#!/usr/bin/env bash
# Displays information about subdomains

dns_config_display () {
    script=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $script" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]; then
	dns_config_display "$1" "www"
	dns_config_display "$1" "lb-01"
	dns_config_display "$1" "web-01"
	dns_config_display "$1" "web-02"
elif [ "$#" == 2 ]; then
	dns_config_display "$1" "$2"
fi
