#!/usr/bin/env bash
# configures Nginx server to another page

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/https://intranet.alxswe.com/projects/266 permanent;"
sudo sed -i "s#server_name _;#$string_for_replacement#" /etc/nginx/sites-enabled/default

service nginx restart
