#!/usr/bin/env bash
# confugures Nginx server to another page

apt apt-get update
apt-get install -y nginx

echo 'server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name lekycollins.tech;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    location / {
        return 404;
    }
}' > /etc/nginx/sites-available/default

service nginx restart
