#!/usr/bin/env bash
# debugging nginx port 80
# create a symbolic link that points to ../sites-enabled/default
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
